### ISSUE TITLE
初音消失的未来

### ISSUE THREAD

**Issue by xxc123456789** [Yuameshi/PhiCommunity-Charts-Repo#14]
# 谱面下载地址

请写出下载地址

# 谱面演示：

给出合适的视频或者第三方视频网站链接
 
# 谱面信息

- 名称
- 代号（不能重复，已有代号请查看此仓库下的文件夹）
- 作曲家
- 音乐文件名称
- EZ/HD/IN/AT定数（只有一个定数则写单定数）
- 判定线贴图（可选）
- EZ/HD/IN/AT文件名（只有一个定数则写单文件）
- 曲绘文件名
- 曲绘画师
- 谱师
- 裁切音频（开始时间）

**Comment by HanHan233** [comment]
？

**Comment by Yuameshi** [comment]
太久未回复
