### ISSUE TITLE
无法加载谱面

### ISSUE THREAD

**Issue by SuSWhW** [Yuameshi/PhiCommunity-Charts-Repo#38]
![image](https://user-images.githubusercontent.com/120356642/207588643-06d36728-6c4f-4a2f-81c1-079ee2e4086b.png)
[cf.phicommunity.com.cn-1671019089579.log](https://github.com/Yuameshi/PhiCommunity-Charts-Repo/files/10227571/cf.phicommunity.com.cn-1671019089579.log)

**Comment by Yuameshi** [comment]
你把json重命名成pec试试吧

**Comment by Yuameshi** [comment]
但也不应该，另一个mpmp也是json的pec没出错，自己差错一下罢（

**Comment by SuSWhW** [comment]
离谱，pr之前检查了很多遍的，应该是没有错的

**Comment by Yuameshi** [comment]
别问我

**Comment by Yuameshi** [comment]
我不知道

**Comment by SuSWhW** [comment]
毁灭吧

**Comment by Yuameshi** [comment]
你是不是rpe写的

**Comment by SuSWhW** [comment]
我不到啊，这谱不是我写的

**Comment by SuSWhW** [comment]
我上传这玩意儿就是单纯想玩，我现在找到模拟器地址了就没管了（

**Comment by Yuameshi** [comment]
6
