### ISSUE TITLE
帮个忙

### ISSUE THREAD

**Issue by BilShiziheng** [Yuameshi/PhiCommunity-Charts-Repo#42]
HanHan大跌
您的旧版Phicom还没删，删一下
http://150.158.43.87/phigros-html5-main/tapToStart/index.html

**Comment by Yuameshi** [comment]
谔谔，这不是我的，我也不知道这是谁的

**Comment by BilShiziheng** [comment]
？草那为什么右下角写着HanHan233我记得这是你的旧的网页版phigros啊

**Comment by Yuameshi** [comment]
> ？草那为什么右下角写着HanHan233我记得这是你的旧的网页版phigros啊

别人部署的而已，我印象中我根本没这个服务器，而且我的phic是放在GitHub/clouflare pages的，和vercel
