### ISSUE TITLE
Bug: Unable to open chart file "Abiogenesis": Getting chart file failed

### ISSUE THREAD

**Issue by shine-yu-student** [yuameshi/PhiCommunity-Charts-Repo#44]
![image](https://user-images.githubusercontent.com/105355837/214781351-1663ef06-d37c-4c87-9db1-63143e638458.png)

But it runs well with phigros simulator:

![image](https://user-images.githubusercontent.com/105355837/214781350-44a62eab-9d1a-4dc2-8ff1-7bfdb3fb6515.png)

**Comment by shine-yu-student** [comment]
@Yuameshi 

Also, the chart "Dingtalk" has this problem too.

**Comment by yuameshi** [comment]
其实，你可以用中文的

**Comment by yuameshi** [comment]
可以参考下readme的rpe谱面特殊处理，转谱rpe再修一下转回来
